# server.port=8181 #properties

server:
  port: 8181

logging:
  level:
    root: info
    com:
      example:
        apibasic:
          req: trace

springdoc:
  swagger-ui:
    path: /myapi.html

#properties
#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=

#database connection
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/demodb
    username: root
    password: mariadb

  #jpa config
  jpa:
    database: mysql # 실제 사용할 dbms 지정
    database-platform: org.hibernate.dialect.MariaDB106Dialect #방언 설정
    show-sql: true #실행되는 sql문 로그를 볼 것 인지
    generate-ddl: true #각 dbms에 맞는 고유 기능을 사용할 지의 여부
    hibernate:
      ddl-auto: create #DDL 문을 처리할 때 설정


#create : 매 실행마다 ddl을 다시 재실행
#update : 매 실행마다 바뀐 부분의 ddl을 alter문으로 수정
#none : ddl을 실행하지 않음 - 운영서버에서는 none으로 둔다.