# server.port=8181 #properties

server:
  port: 8181

logging:
  level:
    root: info
    com:
      example:
        apibasic:
          req: trace

#properties
#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=

#yml
#spring:
#  datasource:
#    url: xxx
#    username: xxx
#    password: xxx