# server.port=8181 #properties

server:
  port: 8181

logging:
  level:
    root: info
    com:
      example:
        apibasic:
          req: trace
    org:
      hibernate: info

springdoc:
  swagger-ui:
    path: /myapi.html

#properties
#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=

#database connection
spring:
  # database connection
  datasource:
    url: jdbc:mariadb://localhost:3306/demodb
    username: root
    password: mariadb
  # jpa config
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB106Dialect # 방언 설정
    show-sql: true # 실행되는 SQL문 로그를 볼 것인지
    hibernate:
      database: mysql # 실제사용할 dbms 지정
      generate-ddl: true # 각 DBMS에 맞는 고유 기능을 사용할 지의 여부
      ddl-auto: create # DDL문을 처리할 때 설정, 실제에서는 None

# create : 매 실행마다 DDL을 다시 재실행
# update : 매 실행마다 바뀐부분의 DDL을 ALTER문으로 수정
# none : DDL을 실행하지 않음  -  운영서버에서는 none으로 둔다.

